### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by danieldanielecki** [AlexPof/mark2epub#2]
Downloaded the sample repository, and created `.epub` file. This works.

However, when trying to open the file with `Kindle Previewer` I can see `Type,"Description", Error,"E20003: No DC-METADATA tag found in opf file.","","","","", Status,"Book conversion failed."`

Additionally, trying to upload https://kdp.amazon.com/en_US/ gives `We couldn't convert your HTML file to Kindle format. Please make sure your file is properly structured. If the problem persists, try uploading your book in a different format. Refer to our formatting guide for more information.`

![Screenshot 2023-08-14 at 11 03 25](https://github.com/AlexPof/mark2epub/assets/12736263/3b4e777e-263c-423b-a180-3f90ebae26ee)

I'm afraid this tool isn't really working at all 👎 :(

**Comment by AlexPof** [comment]
There was indeed a problem with the metadata in the OPF file. This should be fixed with the recent commit.
The sample folder now contains metadata in the 'description.json' file, which are added in the OPF file upon compilation.

As for the second problem, I don't know the details of the processing Amazon is applying, so I can't say what is the exact problem and how to fix it.
